packages:
  - 'packages/*'

catalog:
  vue: '^3.5.17'
  monaco-editor: '^0.52.2'
  typescript: '~5.8.3'
  vite: '^7.0.4'
  '@vitejs/plugin-vue': '^6.0.0'
  '@vue/tsconfig': '^0.7.0'
  vue-tsc: '^2.2.12'